apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.0.7
appVersion: 0.0.7
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
